version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./newssite:/newssite
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    container_name: db
    command: [ mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci ]
    ports:
      - "3306:3306"
    image: mysql:8
    environment:
      - "MYSQL_ROOT_PASSWORD"
      - "MYSQL_DATABASE=newssite"
      - "MYSQL_USER=newssite"
      - "MYSQL_PASSWORD"
