version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  newssite:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./newssite:/newssite
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db