version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
      - "4040:4040"
      - "4041:4041"
    volumes:
      - ./newssite:/newssite
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
