# Generated by Django 3.1.5 on 2021-01-20 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='url_feed',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='article',
            name='site',
        ),
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summarizer.site'),
        ),
    ]
